version: "3.3"
services:

  #nginx
  nginx:
    build: ./nginx/
    container_name: my_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - wp-volume:/www/wordpress
    depends_on:
      - wordpress

  #Wordpress & PHP
  wordpress:
    build: ./wordpress/
    container_name: my_wordpress
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - wp-volume:/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - ./.env

  # DataBase
  mariadb:
    build: ./mariadb/
    container_name: my_mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    env_file:
      - ./.env

  # php adminer  
  adminer:
    build: ./adminer/
    container_name: my_adminer
    restart: always
    ports:
      - "5000:5000"

volumes:
     wp-volume:
