- hosts: master
  become: yes
  tasks:
    - name: Download k3s install script
      get_url:
        url: https://get.k3s.io 
        dest: /home/kube/k3s_install.sh
        mode: a+x
        
    - name: Print the master node's private IP
      ansible.builtin.debug:
        msg: INSTALL_K3S_EXEC="--node-ip {{ hostvars['master'].private_ip }}"  K3S_KUBECONFIG_MODE="644"

    - name: Execute k3s_install.sh
      shell: INSTALL_K3S_EXEC="--node-ip {{ hostvars['master'].private_ip }}"  K3S_KUBECONFIG_MODE="644" /home/kube/k3s_install.sh >> /home/kube/k3s_install_log.txt
      args:
        chdir: /home/kube
        creates: k3s_install_log.txt