# - hosts: master
#   become: yes
#   gather_facts: false
#   tasks:
#     - name: Get node token
#       shell: cat /var/lib/rancher/k3s/server/node-token 
#       register: node_token_output

#     - name: Clean and add node_token to facts
#       set_fact:
#         node_token: "{{ node_token_output.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: Download k3s install script
      get_url:
        url: https://get.k3s.io 
        dest: /home/kube/k3s_install.sh
        mode: a+x

    # - name: Print the master node's private IP
    #   ansible.builtin.debug:
    #     msg: K3S_URL="https://{{ hostvars['master'].private_ip }}:6443" K3S_TOKEN="{{ hostvars['master'].node_token }}" INSTALL_K3S_EXEC="--node-ip {{ hostvars[inventory_hostname].private_ip }}"

    # - name: Join the cluster through the master node's private IP
    #   shell: INSTALL_K3S_EXEC="--node-ip {{ hostvars[inventory_hostname].private_ip }}" K3S_URL="https://{{ hostvars['master'].private_ip }}:6443" K3S_KUBECONFIG_MODE="644" K3S_TOKEN="{{ hostvars['master'].node_token }}" /home/kube/k3s_install.sh >> worker_setup.txt
    #   args:
    #     chdir: /home/kube
    #     creates: worker_setup.txt